Enable CMake Unity build
InfiniTimeOrg/InfiniSim pull request #74
Opened 2022-10-27 19:40 UTC by tnixeu

This PR turns on CMake unity build in the CI.

Some files cause problems with the unity build. This is why I added the `SKIP_UNITY_BUILD_INCLUSION` property to those files.

On my machine the unity build takes about 7s, whereas the normal build takes about 9.5s. In the current GitHub workflow the build takes about 1 minute. So there the seed up might be nice.

The unity build infinisim executable is also just 9.5MB, whereas the normal build is about 11MB.

2022-10-27 19:45 UTC, NeroBurner requested changes
typo and personal preference in formatting

2022-10-27 19:45 UTC, NeroBurner commented on CMakeLists.txt
> +# skip files, which currently cause problems when truning on CMake untiy build
"truning"?

2022-10-27 19:45 UTC, NeroBurner commented on CMakeLists.txt
> +set_source_files_properties(main.cpp ${LVGL_SOURCES} ${InfiniTime_SCREENS} PROPERTIES SKIP_UNITY_BUILD_INCLUSION ON)
just formatting, personal preference of mine

```suggestion
set_source_files_properties(
  main.cpp
  ${LVGL_SOURCES}
  ${InfiniTime_SCREENS}
  PROPERTIES SKIP_UNITY_BUILD_INCLUSION ON)
```

2022-10-27 19:49 UTC, NeroBurner commented
from the unity-excludes files `main.cpp` is the only one in the responsibility of InfiniSim. What would we have to do to make `main.cpp` unity-buildable?

It seems the generated `<font>.c` files need to be excluded as well

2022-10-27 20:51 UTC, tnixeu commented
The build currently breaks because some changes needed in the InfiniTime CMake scripts as well. See more here: https://github.com/InfiniTimeOrg/InfiniTime/pull/1395

2022-10-27 20:58 UTC, tnixeu commented
> from the unity-excludes files `main.cpp` is the only one in the responsibility of InfiniSim. What would we have to do to make `main.cpp` unity-buildable?
> 
> It seems the generated `<font>.c` files need to be excluded as well

The `monitor_t` struct is the problem:
```cpp
extern "C"
{
typedef struct {
  SDL_Window * window;
  SDL_Renderer * renderer;
  SDL_Texture * texture;
  volatile bool sdl_refr_qry;
#if MONITOR_DOUBLE_BUFFERED
  uint32_t * tft_fb_act;
#else
  uint32_t tft_fb[LV_HOR_RES_MAX * LV_VER_RES_MAX];
#endif
}monitor_t;
extern monitor_t monitor;
}
```
The file `sim/displayapp/LittleVgl.cpp` could be skipped in the unity build instead of the `main.cpp`.

2022-10-27 21:17 UTC, NeroBurner approved these changes
the monitor struct is required in the LittleVgl file for simulating the monitor swiping.

So we could move the saveScreenshot and create Gif functions/classes to LittleVgl. But that should be done in a different PR. This one is looking good-ish (except the typo in the comment).

2022-10-27 21:26 UTC, tnixeu commented
Is there a reason why it is in the *.c files and not in a *.h file?

2022-10-27 21:53 UTC, NeroBurner commented
because the definition is from the `lv_drivers` submodule and I'm just hijacking this definition for the InfiniSim needs. And it's in the main.cpp file because it was convenient to put it there instead of creating new files

2023-05-01 19:51 UTC, NeroBurner commented
closing as upstream reverted the unity build PR

2023-05-01 19:51 UTC, closed without merging